### ISSUE TITLE
Surf's up button

### ISSUE THREAD

**Issue by JoshDAO** [fac20/Week-1-PartyWave-CEFG#30]
Not sure what this does at the moment, did you have a plan for it? Slightly misleading at the moment.

**Comment by fairyaksh** [comment]
Yes, we had plans to make it scroll down to the Team section - just used it as a Call To Action button for the header as it made sense for a user to have a button to scroll instead of doing it manually. 

HOWEVER, we didn't have enough time to add this in as it wasn't a priority but thank you for noticing :raised_hands: :two_hearts:
